from util import PreProcessing           


pre_processing = PreProcessing('accident_data.csv')
data = pre_processing.read_csv()
entropia_S = pre_processing.entropy(data)
print(entropia_S)
#print(accident_level_values)
training_data, test_data = pre_processing.separate_data()
print(len(data))
print(len(training_data))
print(len(test_data))

data_gain, data_gain_array = pre_processing.gain('Data')
country_gain, country_gain_array = pre_processing.gain('Country')
local_gain, local_gain_array = pre_processing.gain('Local')
sector_gain, sector_gain_array = pre_processing.gain('Industry Sector')
potential_gain, potential_gain_array = pre_processing.gain('Potential Accident Level')
genre_gain, genre_gain_array = pre_processing.gain('Genre')
employee_gain, employee_gain_array = pre_processing.gain('Employee ou Terceiro')
risco_gain, risco_gain_array = pre_processing.gain('Risco Critico')

print(pre_processing.gain('Data'))
print()
print(pre_processing.gain('Country'))
print()
print(pre_processing.gain('Local'))
print()
print(pre_processing.gain('Industry Sector'))
print()
print(pre_processing.gain('Potential Accident Level'))
print()
print(pre_processing.gain('Genre'))
print()
print(pre_processing.gain('Employee ou Terceiro'))
print()
print(pre_processing.gain('Risco Critico'))
